on:
    workflow_call:
      inputs:
        core:
          description: 'ESP core (esp8266 or esp32)'
          default: 'esp32'
          required: true
          type: string
        board:
          description: 'ESP board'
          default: 'd1_mini32'
          type: string
          required: true
jobs:
    build_eep:
        runs-on: ubuntu-latest
        env:
            SKETCH_NAME: ESP_toggle_LED_Backend
        steps:
          - uses: actions/checkout@v4
            with:
              repository: 'hredan/ESP_toggle_LED_Backend'
              ref: 'update_build_scripts'
          - uses: actions/download-artifact@v4
            with:
              name: data
          - run: ls -la
          - uses: hredan/eep-build-action@main
            with:
              sketch-name: ${{env.SKETCH_NAME}}
              core: ${{ inputs.core }}
              board: ${{ inputs.board}}
              libs: "Dictionary"
          - run: ls -la